In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys
import os
pathap = os.path.join('GENE_ML','gene_ml','static_sparse_grid_approximations')
sys.path.append(pathap)
from GENE_ML.gene_ml.samplers.uniform import Uniform
from GENE_ML.gene_ml.datagen.datagen import DataGen

# check config.py
from config import Config
config = Config()


parameters = ['_grp_species_0-omt','_grp_species_1-omt','species-omn']
bounds = [(4,6.7), (2.1,3.5), (0.16,2.9)] #if bounds is a float rather than tuple then the sampler will make that the only value

num_samples = 20

sampler_uniform = Uniform(parameters=parameters, num_samples=num_samples ,bounds=bounds)

# Folder name for the data to be saved in within the self.remote_save_base_dir of config
remote_save_name = "data_gen_local_test"

# This is used to identify the problem folder in gene
ex_id = 'dglt'

single_run_timelim = 900
single_run_simtimelim = 300

datagen = DataGen(config, sampler_uniform, 
                  ex_id=ex_id, remote_save_name=remote_save_name, 
                  single_run_timelim=single_run_timelim, 
                  single_run_simtimelim=single_run_simtimelim, num_workers=2)



/pfs/lustrep4/projappl/project_462000451/DEEPlasma/GENE_ML/gene_ml/runners/GENErunner.py:103: SyntaxWarning: invalid escape sequence '\d'
  sbatch_id = re.search('(?<![\d])\d{7}(?![\d])', out).group(0)
/pfs/lustrep4/projappl/project_462000451/DEEPlasma/GENE_ML/gene_ml/runners/GENErunner.py:237: SyntaxWarning: invalid escape sequence '\d'
  batch_id = re.search('(?<![\d])\d{7}(?![\d])', out).group(0)


In [5]:
datagen.executor.pre_run_check()


EXECUTOR, PRINT_CHECK_PARAMETERS
 ----------------------------------------------------------------------------------------------------
PRE RUN CHECK


SINGLE RUN TIMELIM 900 N SAMPLES 10
THE ESTIMATED WALLTIME FOR RUN ex-dglt_batch-0 is 00-02:45:00, dd-hh-mm-ss TO RUN 10 SAMPLES
CHECKING IF PROBLEM DIRECTORY EXISTS
PROBLEM DIRECTORY EXISTS
ALTERING THE PARAMETERS FILE IN THE REMOTE PROBLEM DIRECTORY
46 timelim 900
    timelim = 10000

    timelim = 900



CODE RUN: SETTING SIMULATION TIME LIMMIT


47 simtimelim 300
    simtimelim = 350

    simtimelim = 300

SBATCH
WRITE SBATCH
#!/bin/bash -l
## LUMI-C (CPU partition) submit script template
## Submit via: sbatch submit.cmd (parameters below can be overwritten by command line options)
#SBATCH -t 00-02:45:00  ## wallclock limit, dd-hh:mm:ss
#SBATCH -N 1                       # total number of nodes, 2 CPUs with 64 rank each
#SBATCH --ntasks=128      # 64 per CPU (i.e. 128 per node). Additional 2 hyperthreads disabled
#SBATCH --mem=0    

/pfs/lustrep4/projappl/project_462000451/DEEPlasma/GENE_ML/gene_ml/parsers/GENEparser.py:427: SyntaxWarning: invalid escape sequence '\d'
  values = re.findall("(-?\d+\.\d+E[+-]?\d+)", l)#np.array(l.split('  ')"


In [8]:
datagen.executor.start_runs()

/pfs/lustrep4/projappl/project_462000451/DEEPlasma/GENE_ML/gene_ml/runners/GENErunner.py:112: SyntaxWarning: invalid escape sequence '\d'
  sbatch_id = re.search('(?<![\d])\d{7}(?![\d])', out).group(0)
/pfs/lustrep4/projappl/project_462000451/DEEPlasma/GENE_ML/gene_ml/runners/GENErunner.py:246: SyntaxWarning: invalid escape sequence '\d'
  batch_id = re.search('(?<![\d])\d{7}(?![\d])', out).group(0)


EXECUTING BATCHES
PRE RUN CHECK


SINGLE RUN TIMELIM 900 N SAMPLES 10
THE ESTIMATED WALLTIME FOR RUN ex-dglt_batch-0 is 00-02:45:00, dd-hh-mm-ss TO RUN 10 SAMPLES
CHECKING IF PROBLEM DIRECTORY EXISTS
PROBLEM DIRECTORY EXISTS
ALTERING THE PARAMETERS FILE IN THE REMOTE PROBLEM DIRECTORY
46 timelim 900
    timelim = 10000

    timelim = 900



CODE RUN: SETTING SIMULATION TIME LIMMIT


47 simtimelim 300
    simtimelim = 350

    simtimelim = 300

SBATCH
WRITE SBATCH
#!/bin/bash -l
## LUMI-C (CPU partition) submit script template
## Submit via: sbatch submit.cmd (parameters below can be overwritten by command line options)
#SBATCH -t 00-02:45:00  ## wallclock limit, dd-hh:mm:ss
#SBATCH -N 1                       # total number of nodes, 2 CPUs with 64 rank each
#SBATCH --ntasks=128      # 64 per CPU (i.e. 128 per node). Additional 2 hyperthreads disabled
#SBATCH --mem=0                    # Allocate all the memory on each node
#SBATCH -p standard                # all options see: scontrol 

In [ ]:
# from config import Config
# config = Config()
# remote = '/project/project_462000451/gene/auto_prob_ex-dgt7_batch-0/base'
# local = '/home/djdaniel/DEEPlasma/sbatch_base_dp'
# config.paramiko_sftp_client.put(local, remote)  

<class 'paramiko.sftp_file.SFTPFile'>


<SFTPAttributes: [ size=1141 uid=10022324 gid=462000451 mode=0o100660 atime=1735890846 mtime=1735891050 ]>

In [16]:
finished = datagen.executor.check_finished()
print(finished)


CHECKING IF JOBS FINISHED: ['8993188', '8993189']
NONE OF THE INPUTED SBATCH IDs ARE RUNNING


EXECUTOR, CHECK FINISHED True
True


In [ ]:
#Not adapted for local yet
#datagen.executor.check_complete()

In [17]:
print(datagen.remote_save_dir)

/scratch/project_462000451/gene_out/gene_auto/data_gen_local_test


# Loading Data Set Mehthod 1: Growthrate and Frequency

In [18]:
from GENE_ML.gene_ml.dataset.ScanData import ScanData
from config import Config
config = Config()
from GENE_ML.gene_ml.parsers.GENEparser import GENE_scan_parser
parser = GENE_scan_parser(config)
# remote_save_dir='/scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7'
remote_save_dir=datagen.remote_save_dir

data_set = ScanData(name='data_gen_tutorial7', config=config, parser=parser, host=config.host, remote_save_dir=remote_save_dir,  test_percentage=50)


Initialising dataset
SSH PATH lumi:/scratch/project_462000451/gene_out/gene_auto/data_gen_local_test
SCAN LOG PATH /pfs/lustrep4/projappl/project_462000451/DEEPlasma/scanlogs/data_gen_tutorial7
MAKING SCANLOG DIR
RETRIEVING REMOTE SCANLOG FILES

RETRIEVING SCANLOG/S VIA scp FROM REMOTE
SCANLOG PATH: lumi:/scratch/project_462000451/gene_out/gene_auto/data_gen_local_test
GETTING ALL SCANLOGS
RETRIVING FROM REMOTE DIR
[256]


ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known


[256, 256]
[256, 256, 256]
[256, 256, 256, 256]


ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known


[256, 256, 256, 256, 256]
[256, 256, 256, 256, 256, 256]
THE ABOVE ERROR IS EXPECTED
SCANLOG/S RETRIEVED AND SAVED TO:/pfs/lustrep4/projappl/project_462000451/DEEPlasma/scanlogs/data_gen_tutorial7

LOADING FROM SCANLOG DIR: /pfs/lustrep4/projappl/project_462000451/DEEPlasma/scanlogs/data_gen_tutorial7
LOG PATHS []


ssh: Could not resolve hostname lumi: Name or service not known
ssh: Could not resolve hostname lumi: Name or service not known


ValueError: Daniel Jordan Says: There is nothing to concatenate into the dataframe. This could be because the scanlog folder is empty or has the incorrect syntax.

In [18]:
data_set.df

run_time      omt2      omt1      omn1 growthrate frequency
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600

In [19]:
data_set.x

array([[3.491141 , 4.499231 , 1.868744 ],
       [3.09027  , 4.539037 , 2.521974 ],
       [2.134392 , 6.083308 , 2.495368 ],
       [3.343549 , 5.836209 , 1.698337 ],
       [3.224416 , 5.275577 , 1.956014 ],
       [3.125924 , 6.471158 , 0.9559793],
       [2.10681  , 5.960762 , 0.9420788],
       [2.754898 , 4.186166 , 0.7953315],
       [2.780213 , 5.508589 , 2.524604 ],
       [2.390622 , 6.352449 , 2.364465 ]])

In [20]:
data_set.x_train, data_set.growthrate_train

(array([[2.780213 , 5.508589 , 2.524604 ],
        [3.491141 , 4.499231 , 1.868744 ],
        [2.390622 , 6.352449 , 2.364465 ],
        [2.10681  , 5.960762 , 0.9420788],
        [2.754898 , 4.186166 , 0.7953315]]),
 array([0.13 , 0.118, 0.162, 0.151, 0.15 ]))

In [21]:
data_set.x_test, data_set.growthrate_test

(array([[2.134392 , 6.083308 , 2.495368 ],
        [3.09027  , 4.539037 , 2.521974 ],
        [3.224416 , 5.275577 , 1.956014 ],
        [3.125924 , 6.471158 , 0.9559793],
        [3.343549 , 5.836209 , 1.698337 ]]),
 array([0.137, 0.086, 0.131, 0.205, 0.171]))

# Loading data already saved in scanlogs


In [ ]:
from GENE_ML.gene_ml.parsers.GENEparser import GENE_scan_parser
from config import Config
config = Config()

parser = GENE_scan_parser(config)

data_set = ScanData('data_gen_tutorial7', config=config, parser=parser, host=None, remote_save_dir=None,  test_percentage=50)

<class 'paramiko.sftp_file.SFTPFile'>
Initialising dataset
SSH PATH None:None
SCAN LOG PATH /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7

LOADING FROM SCANLOG DIR: /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7
LOG PATHS ['geneerr_batch-0_scanfiles-0.log' 'geneerr_batch-1_scanfiles-0.log'
 'scan_batch-0_scanfiles-0.log' 'scan_batch-1_scanfiles-0.log']

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-0_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-0_scanfiles-0.log

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-1_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-1_scanfiles-0.log

10 SAMPLES RAN OUT OF 10 BEFORE MAX WALLTIME:
NUMBER OF SAMPLES AFTER REMOVING NaN's: 10
NaN PERCENTAGE =  0.0
SETTING VARIABLES

RANDOMLY SPLITTING DATA INTO TEST AND TRAINING SETS: 50% test, 50 t

/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df_inc_nan = pd.concat(dfs_inc_nans)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs), np.sum(n_samp_all), np.sum(n_requested_all), np.sum(n_samp_nonan_all)


In [25]:
data_set.df

run_time      omt2      omt1      omn1 growthrate frequency
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600

# Combine datasets

In [28]:
data_set_1 = ScanData('data_gen_tutorial7', config=config, parser=parser, host=None, remote_save_dir=None,  test_percentage=50)
data_set_2 = ScanData('data_gen_tutorial7', config=config, parser=parser, host=None, remote_save_dir=None,  test_percentage=50)

data_set_3 = data_set_1.concat([data_set_2])

data_set_3.df

Initialising dataset
SSH PATH None:None
SCAN LOG PATH /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7

LOADING FROM SCANLOG DIR: /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7
LOG PATHS ['geneerr_batch-0_scanfiles-0.log' 'geneerr_batch-1_scanfiles-0.log'
 'scan_batch-0_scanfiles-0.log' 'scan_batch-1_scanfiles-0.log']

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-0_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-0_scanfiles-0.log

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-1_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-1_scanfiles-0.log

10 SAMPLES RAN OUT OF 10 BEFORE MAX WALLTIME:
NUMBER OF SAMPLES AFTER REMOVING NaN's: 10
NaN PERCENTAGE =  0.0
SETTING VARIABLES

RANDOMLY SPLITTING DATA INTO TEST AND TRAINING SETS: 50% test, 50 training.
Initialising dataset
SSH PATH

/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df_inc_nan = pd.concat(dfs_inc_nans)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs), np.sum(n_samp_all), np.sum(n_requested_all), np.sum(n_samp_nonan_all)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA

run_time      omt2      omt1      omn1 growthrate frequency
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600

# Loading Data Set Method 2: Categorisation and more
Has some bugs

## Save all GENE out to vault

In [29]:
datagen.executor.local_backup()

In [20]:
from GENE_ML.gene_ml.dataset.ScanData import ScanData2
from config import Config
config = Config()
from GENE_ML.gene_ml.parsers.GENEparser import GENE_scan_parser
parser = GENE_scan_parser(config)
# save_dir = '/home/djdaniel/DEEPlasma/vault/data_gen_tutorial7'
save_dir=datagen.remote_save_dir
data_set = ScanData2(name='data_gen_tutorial7', config=config, parser=parser, save_dir=save_dir,  split_ratio=[0,0,1], categorise=True)


Initialising dataset
DEBUG2 /scratch/project_462000451/gene_out/gene_auto/data_gen_local_test/ex-dglt_batch-0/scanfiles0000
HIT SIM LIMIT TEST ON FILE: /scratch/project_462000451/gene_out/gene_auto/data_gen_local_test/ex-dglt_batch-0/scanfiles0000/geneerr.log
line   0: *** entering time loop ***

hstlt, len stat and run_count 0 0
line   0: *** entering time loop ***

hstlt, len stat and run_count 1 1
line   0: *** entering time loop ***

hstlt, len stat and run_count 2 2
line   0: *** entering time loop ***

hstlt, len stat and run_count 3 3
line   0: *** entering time loop ***

hstlt, len stat and run_count 4 4
line   0: *** entering time loop ***

hstlt, len stat and run_count 5 5
line   0: *** entering time loop ***

hstlt, len stat and run_count 6 6
line   0: *** entering time loop ***

hstlt, len stat and run_count 7 7
line   0: *** entering time loop ***

hstlt, len stat and run_count 8 8
line   0: *** entering time loop ***

hstlt, len stat and run_count 9 9
There have been 0 un

/pfs/lustrep4/projappl/project_462000451/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:369: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rest_df_no_nan['data_categorie'] = random_categories


In [21]:
data_set.df

omt2      omt1      omn1 growthrate frequency run_time  \
0   3.491141  4.499231  1.868744     0.1180    0.4570   24.881   
1   3.090270  4.539037  2.521974     0.0860    0.3430   21.475   
2   2.134392  6.083308  2.495368     0.1370    0.4200   27.047   
3   3.343549  5.836209  1.698337     0.1710    0.5400   26.282   
4   3.224416  5.275577  1.956014     0.1310    0.4630   24.707   
5   3.125924  6.471158  0.955979     0.2050    0.7180   32.585   
6   2.106810  5.960762  0.942079     0.1510    0.6350   42.326   
7   2.754898  4.186166  0.795331     0.1500    0.6580   24.638   
8   2.780213  5.508589  2.524604     0.1300    0.3810   19.974   
9   2.390622  6.352449  2.364465     0.1620    0.4600   25.271   
10  2.865373  5.208966  1.367448        NaN       NaN  134.122   
11  3.152980  6.349830  1.208299     0.1960    0.6620   32.132   
12  2.930616  5.935637  2.332955     0.1580    0.4370   22.124   
13  2.304782  4.166247  2.887675     0.0400    0.2530   54.939   
14  2.246194  4.881863  0.604047        NaN       NaN  129.473   
15  2.923647  4.638321  0.291560     0.2100    0.7680   18.701   
16  3.214764  6.288004  2.058218     0.1870    0.5030   22.007   
17  3.395621  5.567226  1.453982     0.1610    0.5710   28.772   
18  3.026653  5.268453  2.382485     0.1250    0.3910   22.068   
19  2.515348  4.189075  1.204802        NaN       NaN  130.499   

      termination_reason fingerprint  ratio_iheat_eheat  \
0   growthrate_converged      [None]           3.046760   
1   growthrate_converged      [None]          -1.610241   
2   growthrate_converged      [None]          -1.018911   
3   growthrate_converged      [None]          21.877296   
4   growthrate_converged      [None]         -34.826949   
5   growthrate_converged      [None]           8.073163   
6   growthrate_converged      [None]          -4.012876   
7   growthrate_converged      [None]           2.167306   
8   growthrate_converged      [None]          -1.642958   
9   growthrate_converged      [None]          -1.467756   
10            simtimelim      [None]           7.246097   
11  growthrate_converged      [None]          13.476537   
12  growthrate_converged      [None]          -2.693078   
13  growthrate_converged      [None]          -0.054963   
14            simtimelim      [None]          14.236292   
15  growthrate_converged      [None]           1.620603   
16  growthrate_converged      [None]          -6.474398   
17  growthrate_converged      [None]           5.142978   
18  growthrate_converged      [None]          -2.646892   
19            simtimelim      [None]          56.368742   

    ratio_eparticle_eheat  ... particle_electromagnetic_ion  \
0               10.673379  ...                -1.223300e+01   
1               -6.759485  ...                -1.747700e-01   
2               -1.807460  ...                -1.755700e+03   
3               43.645584  ...                -8.520400e+04   
4              -80.315166  ...                -3.329500e+02   
5               19.870748  ...                -1.774800e+09   
6               -9.694186  ...                -4.567300e+07   
7               11.332764  ...                -9.579400e+02   
8               -3.576447  ...                -1.165600e+01   
9               -2.485665  ...                -8.313100e+03   
10              19.057844  ...                -2.984500e+22   
11              29.082521  ...                -1.123400e+08   
12              -4.955266  ...                -5.043700e+02   
13              -1.710592  ...                 1.682100e+00   
14              34.331779  ...                -9.911900e+25   
15              14.415011  ...                -2.231400e+03   
16             -11.160618  ...                -7.431700e+03   
17              11.911101  ...                -1.010700e+05   
18              -6.247592  ...                -1.942600e+01   
19             265.618628  ...                -1.983800e+15   

    heat_electrostatic_ion  heat_electromagnetic_ion  \
0