In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
pathap = os.path.join('GENE_ML','gene_ml','static_sparse_grid_approximations')
sys.path.append(pathap)
from GENE_ML.gene_ml.samplers.uniform import Uniform
from GENE_ML.gene_ml.datagen.datagen import DataGen

# check config.py
from config import Config
config = Config()


parameters = ['_grp_species_0-omt','_grp_species_1-omt','species-omn']
bounds = [(4,6.7), (2.1,3.5), (0.16,2.9)] #if bounds is a float rather than tuple then the sampler will make that the only value

num_samples = 20

sampler_uniform = Uniform(parameters=parameters, num_samples=num_samples ,bounds=bounds)

# Folder name for the data to be saved in within the self.remote_save_base_dir of config
remote_save_name = "data_gen_tutorial7"

# This is used to identify the problem folder in gene
ex_id = 'dgt7'

single_run_timelim = 900
single_run_simtimelim = 300

datagen = DataGen(config, sampler_uniform, 
                  ex_id=ex_id, remote_save_name=remote_save_name, 
                  single_run_timelim=single_run_timelim, 
                  single_run_simtimelim=single_run_simtimelim, num_workers=2)



/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/parsers/GENEparser.py:425: SyntaxWarning: invalid escape sequence '\d'
  values = re.findall("(-?\d+\.\d+E[+-]?\d+)", l)#np.array(l.split('  ')"
/home/djdaniel/anaconda3/envs/gene_ml/lib/python3.12/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/djdaniel/anaconda3/envs/gene_ml/lib/python3.12/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
  "class": algorithms.Blowfish,
/home/djdaniel/anaconda3/envs/gene_ml/lib/python3.12/site-packages/paramiko/transport.py:243: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from

<class 'paramiko.sftp_file.SFTPFile'>


In [9]:
datagen.executor.pre_run_check()


EXECUTOR, PRINT_CHECK_PARAMETERS
 ----------------------------------------------------------------------------------------------------
PRE RUN CHECK


SINGLE RUN TIMELIM 900 N SAMPLES 10
THE ESTIMATED WALLTIME FOR RUN ex-dgt7_batch-0 is 00-02:45:00, dd-hh-mm-ss TO RUN 10 SAMPLES
CHECKING IF PROBLEM DIRECTORY EXISTS?
PLACING BASE PARAMETERS AND SBATCH TO REMOTE PROBLEM DIRECTORY
DEBUG, PATH /home/djdaniel/DEEPlasma/sbatch_base_dp /project/project_462000451/gene/auto_prob_ex-dgt7_batch-0/submit.cmd
ALTERING THE PARAMETERS FILE IN THE REMOTE PROBLEM DIRECTORY
46 timelim 900
    timelim = 10000

    timelim = 900



CODE RUN: SETTING SIMULATION TIME LIMMIT


47 simtimelim 300
    simtimelim = 350

    simtimelim = 300

SBATCH
WRITE SBATCH
#!/bin/bash -l
## LUMI-C (CPU partition) submit script template
## Submit via: sbatch submit.cmd (parameters below can be overwritten by command line options)
#SBATCH -t 00-02:45:00  ## wallclock limit, dd-hh:mm:ss
#SBATCH -N 1                       # to

In [10]:
datagen.executor.start_runs()

EXECUTING BATCHES
PRE RUN CHECK


SINGLE RUN TIMELIM 900 N SAMPLES 10
THE ESTIMATED WALLTIME FOR RUN ex-dgt7_batch-0 is 00-02:45:00, dd-hh-mm-ss TO RUN 10 SAMPLES
CHECKING IF PROBLEM DIRECTORY EXISTS?
PLACING BASE PARAMETERS AND SBATCH TO REMOTE PROBLEM DIRECTORY
DEBUG, PATH /home/djdaniel/DEEPlasma/sbatch_base_dp /project/project_462000451/gene/auto_prob_ex-dgt7_batch-0/submit.cmd
ALTERING THE PARAMETERS FILE IN THE REMOTE PROBLEM DIRECTORY
46 timelim 900
    timelim = 10000

    timelim = 900



CODE RUN: SETTING SIMULATION TIME LIMMIT


47 simtimelim 300
    simtimelim = 350

    simtimelim = 300

SBATCH
WRITE SBATCH
#!/bin/bash -l
## LUMI-C (CPU partition) submit script template
## Submit via: sbatch submit.cmd (parameters below can be overwritten by command line options)
#SBATCH -t 00-02:45:00  ## wallclock limit, dd-hh:mm:ss
#SBATCH -N 1                       # total number of nodes, 2 CPUs with 64 rank each
#SBATCH --ntasks=128      # 64 per CPU (i.e. 128 per node). Additional 2

In [ ]:
# from config import Config
# config = Config()
# remote = '/project/project_462000451/gene/auto_prob_ex-dgt7_batch-0/base'
# local = '/home/djdaniel/DEEPlasma/sbatch_base_dp'
# config.paramiko_sftp_client.put(local, remote)  

<class 'paramiko.sftp_file.SFTPFile'>


<SFTPAttributes: [ size=1141 uid=10022324 gid=462000451 mode=0o100660 atime=1735890846 mtime=1735891050 ]>

In [15]:
finished = datagen.executor.check_finished()
print(finished)


CHECKING IF JOBS FINISHED: ['8970695', '8970698']
NONE OF THE INPUTED SBATCH IDs ARE RUNNING


EXECUTOR, CHECK FINISHED True
True


In [16]:
datagen.executor.check_complete()

FileNotFoundError: [Errno 2] No such file or directory: '/scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/ex-dgt7_batch-1/scanfiles0000/in_par/gene_status'

In [23]:
print(datagen.remote_save_dir)

/scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial6


# Loading Data Set Mehthod 1: Growthrate and Frequency

In [17]:
from GENE_ML.gene_ml.dataset.ScanData import ScanData
from config import Config
config = Config()
from GENE_ML.gene_ml.parsers.GENEparser import GENE_scan_parser
parser = GENE_scan_parser(config)
remote_save_dir='/scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7'#datagen.remote_save_dir

data_set = ScanData(name='data_gen_tutorial7', config=config, parser=parser, host=config.host, remote_save_dir=remote_save_dir,  test_percentage=50)


<class 'paramiko.sftp_file.SFTPFile'>
Initialising dataset
SSH PATH lumi:/scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7
SCAN LOG PATH /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7
MAKING SCANLOG DIR
RETRIEVING REMOTE SCANLOG FILES

RETRIEVING SCANLOG/S VIA scp FROM REMOTE
SCANLOG PATH: lumi:/scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7
GETTING ALL SCANLOGS
RETRIVING FROM REMOTE DIR
[0]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*0/scanfiles*1/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*0/scanfiles*1/geneerr.log: No such file or directory


[0, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*0/scanfiles*2/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*0/scanfiles*2/geneerr.log: No such file or directory


[0, 256, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*0/scanfiles*3/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*0/scanfiles*3/geneerr.log: No such file or directory


[0, 256, 256, 256]
[0, 256, 256, 256, 0]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*1/scanfiles*1/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*1/scanfiles*1/geneerr.log: No such file or directory


[0, 256, 256, 256, 0, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*1/scanfiles*2/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*1/scanfiles*2/geneerr.log: No such file or directory


[0, 256, 256, 256, 0, 256, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*1/scanfiles*3/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*1/scanfiles*3/geneerr.log: No such file or directory


[0, 256, 256, 256, 0, 256, 256, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*2/scanfiles*0/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*2/scanfiles*0/geneerr.log: No such file or directory


[0, 256, 256, 256, 0, 256, 256, 256, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*3/scanfiles*0/scan.log: No such file or directory
scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*3/scanfiles*0/geneerr.log: No such file or directory


[0, 256, 256, 256, 0, 256, 256, 256, 256, 256]


scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*4/scanfiles*0/scan.log: No such file or directory


[0, 256, 256, 256, 0, 256, 256, 256, 256, 256, 256]
THE ABOVE ERROR IS EXPECTED
SCANLOG/S RETRIEVED AND SAVED TO:/home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7

LOADING FROM SCANLOG DIR: /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7
LOG PATHS ['geneerr_batch-0_scanfiles-0.log' 'geneerr_batch-1_scanfiles-0.log'
 'scan_batch-0_scanfiles-0.log' 'scan_batch-1_scanfiles-0.log']

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-0_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-0_scanfiles-0.log

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-1_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-1_scanfiles-0.log

10 SAMPLES RAN OUT OF 10 BEFORE MAX WALLTIME:
NUMBER OF SAMPLES AFTER REMOVING NaN's: 10
NaN PERCENTAGE =  0.0
SETTING VARIABLES

RANDOMLY SPLITTING DATA INTO TEST AND TRAINING

scp: /scratch/project_462000451/gene_out/gene_auto/data_gen_tutorial7/*batch*4/scanfiles*0/geneerr.log: No such file or directory
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df_inc_nan = pd.concat(dfs_inc_nans)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs), np.sum(n_samp_all), np.sum(n_requested_all), np.sum(n_samp_nonan_all)


In [18]:
data_set.df

run_time      omt2      omt1      omn1 growthrate frequency
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600

In [19]:
data_set.x

array([[3.491141 , 4.499231 , 1.868744 ],
       [3.09027  , 4.539037 , 2.521974 ],
       [2.134392 , 6.083308 , 2.495368 ],
       [3.343549 , 5.836209 , 1.698337 ],
       [3.224416 , 5.275577 , 1.956014 ],
       [3.125924 , 6.471158 , 0.9559793],
       [2.10681  , 5.960762 , 0.9420788],
       [2.754898 , 4.186166 , 0.7953315],
       [2.780213 , 5.508589 , 2.524604 ],
       [2.390622 , 6.352449 , 2.364465 ]])

In [20]:
data_set.x_train, data_set.growthrate_train

(array([[2.780213 , 5.508589 , 2.524604 ],
        [3.491141 , 4.499231 , 1.868744 ],
        [2.390622 , 6.352449 , 2.364465 ],
        [2.10681  , 5.960762 , 0.9420788],
        [2.754898 , 4.186166 , 0.7953315]]),
 array([0.13 , 0.118, 0.162, 0.151, 0.15 ]))

In [21]:
data_set.x_test, data_set.growthrate_test

(array([[2.134392 , 6.083308 , 2.495368 ],
        [3.09027  , 4.539037 , 2.521974 ],
        [3.224416 , 5.275577 , 1.956014 ],
        [3.125924 , 6.471158 , 0.9559793],
        [3.343549 , 5.836209 , 1.698337 ]]),
 array([0.137, 0.086, 0.131, 0.205, 0.171]))

# Loading data already saved in scanlogs


In [ ]:
from GENE_ML.gene_ml.parsers.GENEparser import GENE_scan_parser
from config import Config
config = Config()

parser = GENE_scan_parser(config)

data_set = ScanData('data_gen_tutorial7', config=config, parser=parser, host=None, remote_save_dir=None,  test_percentage=50)

<class 'paramiko.sftp_file.SFTPFile'>
Initialising dataset
SSH PATH None:None
SCAN LOG PATH /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7

LOADING FROM SCANLOG DIR: /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7
LOG PATHS ['geneerr_batch-0_scanfiles-0.log' 'geneerr_batch-1_scanfiles-0.log'
 'scan_batch-0_scanfiles-0.log' 'scan_batch-1_scanfiles-0.log']

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-0_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-0_scanfiles-0.log

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-1_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-1_scanfiles-0.log

10 SAMPLES RAN OUT OF 10 BEFORE MAX WALLTIME:
NUMBER OF SAMPLES AFTER REMOVING NaN's: 10
NaN PERCENTAGE =  0.0
SETTING VARIABLES

RANDOMLY SPLITTING DATA INTO TEST AND TRAINING SETS: 50% test, 50 t

/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df_inc_nan = pd.concat(dfs_inc_nans)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs), np.sum(n_samp_all), np.sum(n_requested_all), np.sum(n_samp_nonan_all)


In [25]:
data_set.df

run_time      omt2      omt1      omn1 growthrate frequency
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600

# Combine datasets

In [28]:
data_set_1 = ScanData('data_gen_tutorial7', config=config, parser=parser, host=None, remote_save_dir=None,  test_percentage=50)
data_set_2 = ScanData('data_gen_tutorial7', config=config, parser=parser, host=None, remote_save_dir=None,  test_percentage=50)

data_set_3 = data_set_1.concat([data_set_2])

data_set_3.df

Initialising dataset
SSH PATH None:None
SCAN LOG PATH /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7

LOADING FROM SCANLOG DIR: /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7
LOG PATHS ['geneerr_batch-0_scanfiles-0.log' 'geneerr_batch-1_scanfiles-0.log'
 'scan_batch-0_scanfiles-0.log' 'scan_batch-1_scanfiles-0.log']

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-0_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-0_scanfiles-0.log

LOADING SCANLOG AND TIME INTO PANDAS DATAFRAME /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/scan_batch-1_scanfiles-0.log : /home/djdaniel/DEEPlasma/scanlogs/data_gen_tutorial7/geneerr_batch-1_scanfiles-0.log

10 SAMPLES RAN OUT OF 10 BEFORE MAX WALLTIME:
NUMBER OF SAMPLES AFTER REMOVING NaN's: 10
NaN PERCENTAGE =  0.0
SETTING VARIABLES

RANDOMLY SPLITTING DATA INTO TEST AND TRAINING SETS: 50% test, 50 training.
Initialising dataset
SSH PATH

/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df_inc_nan = pd.concat(dfs_inc_nans)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs), np.sum(n_samp_all), np.sum(n_requested_all), np.sum(n_samp_nonan_all)
/home/djdaniel/DEEPlasma/GENE_ML/gene_ml/dataset/ScanData.py:213: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA

run_time      omt2      omt1      omn1 growthrate frequency
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600
0   24.582  3.491141  4.499231  1.868744     0.1180    0.4570
1   21.433  3.090270  4.539037  2.521974     0.0860    0.3430
2   26.437  2.134392  6.083308  2.495368     0.1370    0.4200
3   26.268  3.343549  5.836209  1.698337     0.1710    0.5400
4   24.516  3.224416  5.275577  1.956014     0.1310    0.4630
5   32.763  3.125924  6.471158  0.955979     0.2050    0.7180
6   42.197  2.106810  5.960762  0.942079     0.1510    0.6350
7   24.592  2.754898  4.186166  0.795331     0.1500    0.6580
8   19.723  2.780213  5.508589  2.524604     0.1300    0.3810
9   24.556  2.390622  6.352449  2.364465     0.1620    0.4600

# Loading Data Set Method 2: Categorisation and more
Has some bugs

## Save all GENE out to vault

In [29]:
datagen.executor.local_backup()

In [40]:
from GENE_ML.gene_ml.dataset.ScanData import ScanData2
from config import Config
config = Config()
from GENE_ML.gene_ml.parsers.GENEparser import GENE_scan_parser
parser = GENE_scan_parser(config)
save_dir = '/home/djdaniel/DEEPlasma/vault/data_gen_tutorial7'
#remote_save_dir=datagen.remote_save_dir
data_set = ScanData2(name='data_gen_tutorial7', config=config, parser=parser, save_dir=save_dir,  split_ratio=[0,0,1], categorise=True)


<class 'paramiko.sftp_file.SFTPFile'>
Initialising dataset
DEBUG2 /home/djdaniel/DEEPlasma/vault/data_gen_tutorial7/ex-dgt7_batch-0/scanfiles0000
HIT SIM LIMIT TEST ON FILE: /home/djdaniel/DEEPlasma/vault/data_gen_tutorial7/ex-dgt7_batch-0/scanfiles0000/geneerr.log
line   0: *** entering time loop ***

hstlt, len stat and run_count 0 0
line   0: *** entering time loop ***

hstlt, len stat and run_count 1 1
line   0: *** entering time loop ***

hstlt, len stat and run_count 2 2
line   0: *** entering time loop ***

hstlt, len stat and run_count 3 3
line   0: *** entering time loop ***

hstlt, len stat and run_count 4 4
line   0: *** entering time loop ***

hstlt, len stat and run_count 5 5
line   0: *** entering time loop ***

hstlt, len stat and run_count 6 6
line   0: *** entering time loop ***

hstlt, len stat and run_count 7 7
line   0: *** entering time loop ***

hstlt, len stat and run_count 8 8
line   0: *** entering time loop ***

hstlt, len stat and run_count 9 9
There have bee

In [41]:
data_set.df

omt2      omt1      omn1 growthrate frequency run_time  \
0  3.491141  4.499231  1.868744     0.1180    0.4570   24.582   
1  3.090270  4.539037  2.521974     0.0860    0.3430   21.433   
2  2.134392  6.083308  2.495368     0.1370    0.4200   26.437   
3  3.343549  5.836209  1.698337     0.1710    0.5400   26.268   
4  3.224416  5.275577  1.956014     0.1310    0.4630   24.516   
5  3.125924  6.471158  0.955979     0.2050    0.7180   32.763   
6  2.106810  5.960762  0.942079     0.1510    0.6350   42.197   
7  2.754898  4.186166  0.795331     0.1500    0.6580   24.592   
8  2.780213  5.508589  2.524604     0.1300    0.3810   19.723   
9  2.390622  6.352449  2.364465     0.1620    0.4600   24.556   

     termination_reason fingerprint  ratio_iheat_eheat  ratio_eparticle_eheat  \
0  growthrate_converged      [None]           3.046760              10.673379   
1  growthrate_converged      [None]          -1.610241              -6.759485   
2  growthrate_converged      [None]          -1.018911              -1.807460   
3  growthrate_converged      [None]          21.877296              43.645584   
4  growthrate_converged      [None]         -34.826949             -80.315166   
5  growthrate_converged      [None]           8.073163              19.870748   
6  growthrate_converged      [None]          -4.012876              -9.694186   
7  growthrate_converged      [None]           2.167306              11.332764   
8  growthrate_converged      [None]          -1.642958              -3.576447   
9  growthrate_converged      [None]          -1.467756              -2.485665   

   ... heat_flux_electron  particle_electrostatic_ion  \
0  ...       1.444640e+03                4.434500e+02   
1  ...       3.050080e+01                1.173900e+01   
2  ...       3.524440e+04                1.891800e+04   
3  ...       2.806930e+06                9.935100e+05   
4  ...       1.489410e+04                5.366400e+03   
5  ...       5.875100e+10                1.942200e+10   
6  ...       7.332300e+09                2.933900e+09   
7  ...       1.590240e+05                4.499200e+04   
8  ...       3.825110e+02                1.720900e+02   
9  ...       1.676090e+05                8.496800e+04   

   particle_electromagnetic_ion  heat_electrostatic_ion  \
0                 -1.223300e+01            2.101300e+03   
1                 -1.747700e-01            4.859000e+01   
2                 -1.755700e+03            1.142000e+05   
3                 -8.520400e+04            6.790300e+06   
4                 -3.329500e+02            3.060900e+04   
5                 -1.774800e+09            1.745900e+11   
6                 -4.567300e+07            2.675500e+10   
7                 -9.579400e+02            2.491300e+05   
8                 -1.165600e+01            9.155100e+02   
9                 -8.313100e+03            5.512100e+05   

   heat_electromagnetic_ion  particle_electrostatic_electron  \
0              2.092200e+01                     4.434500e+02   
1              1.596300e+00                     1.173900e+01   
2             -3.206700e+03                     1.891800e+04   
3             -2.043400e+05                     9.935100e+05   
4             -3.749800e+02                     5.366400e+03   
5             -5.826800e+09                     1.942200e+10   
6              1.395400e+07                     2.933900e+09   
7             -7.792700e+02                     4.499200e+04   
8             -1.219600e+01                     1.720900e+02   
9             -1.887000e+04                     8.496800e+04   

   particle_electromagnetic_electron  heat_electrostatic_electron  \
0                      -1.223300e+01                 1.550300e+03   
1                      -1.747700e-01                 3.226400e+01   
2                      -1.755700e+03                 4.183000e+04   
3                      -8.520400e+04                 3.343800e+06   
4                      -3.329500e+02                 1.694800e+04   
5 